### ISSUE TITLE
make test ERROR

### ISSUE THREAD

**Issue by WaxRain** [nanoporetech/pyguppyclient#5]
When I install pyguppyclient to connect Guppy,  Errors occurred.

system: Ubuntu16.04
python: 3.7.4.
Guppy: v4.2.2 or v4.4.1, I've tried 2 versions
pyguppyclent: v0.0.6 or v0.07a

```
(venv3)software/pyguppyclient$ make test
mkdir -p tests/reads
wget -q --show-progress --max-redirect=9 -O tests/reads/reads.tar.gz https://nan                                          oporetech.box.com/shared/static/hpeyme4posfzmc0hcxh0nl5tiuzjfbzf.gz
tests/reads/reads.t 100%[===================>]  15.45M  96.9KB/s    in 2m 42s
tar xf tests/reads/reads.tar.gz -C tests/reads
rm tests/reads/reads.tar.gz
nosetests -v --with-doctest --with-coverage --cover-package pyguppyclient
Doctest: pyguppyclient.utils.bases_fmt ... ok
Doctest: pyguppyclient.utils.batches ... ok
Doctest: pyguppyclient.utils.distribute ... ok
Doctest: pyguppyclient.utils.parse_config ... ok
test the caller ... ERROR
test loaded configs ... ERROR
try and load in invalid config ... ERROR
test a read with state ... ERROR
test a read without state ... ERROR
test the client api without sending a read ... ERROR

======================================================================
ERROR: test the caller
----------------------------------------------------------------------
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py"                                          , line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py"                                          , line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py"                                          , line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/caller.py",                                           line 74, in basecall_batch
    with GuppyBasecallerClient(config_name=self.config, host=self.host, port=sel                                          f.port) as client:
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/client.py",                                           line 43, in __enter__
    self.connect()
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/client.py",                                           line 81, in connect
    self.pcl_client.get_error_message())
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get det                                          ails from server (invalid response).
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/tests/caller_tests.py", li                                          ne 19, in test_caller
    caller.basecall(self.files)
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/caller.py",                                           line 61, in basecall
    return sum(pool.map(self.basecall_batch, work))
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py"                                          , line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py",                                           line 598, in result_iterator
    yield fs.pop().result()
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py",                                           line 435, in result
    return self.__get_result()
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py",                                           line 384, in __get_result
    raise self._exception
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get det                                          ails from server (invalid response).

======================================================================
ERROR: test loaded configs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/tests/client_tests.py", li                                          ne 20, in setUp
    self.client.connect()
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/client.py",                                           line 81, in connect
    self.pcl_client.get_error_message())
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get det                                          ails from server (invalid response).

======================================================================
ERROR: try and load in invalid config
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/tests/client_tests.py", li                                          ne 20, in setUp
    self.client.connect()
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/client.py",                                           line 81, in connect
    self.pcl_client.get_error_message())
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get det                                          ails from server (invalid response).

======================================================================
ERROR: test a read with state
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/tests/client_tests.py", li                                          ne 20, in setUp
    self.client.connect()
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/client.py",                                           line 81, in connect
    self.pcl_client.get_error_message())
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get det                                          ails from server (invalid response).

======================================================================
ERROR: test a read without state
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/tests/client_tests.py", li                                          ne 20, in setUp
    self.client.connect()
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/client.py",                                           line 81, in connect
    self.pcl_client.get_error_message())
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get det                                          ails from server (invalid response).

======================================================================
ERROR: test the client api without sending a read
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/tests/client_tests.py", li                                          ne 20, in setUp
    self.client.connect()
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/pyguppyclient/client.py",                                           line 81, in connect
    self.pcl_client.get_error_message())
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get det                                          ails from server (invalid response).

Name                                                   Stmts   Miss  Cover   Mis                                          sing
--------------------------------------------------------------------------------                                          ----
pyguppyclient/__init__.py                                  7      0   100%
pyguppyclient/caller.py                                   47     17    64%   70-                                          94
pyguppyclient/client.py                                  147     83    44%   43-                                          44, 47, 50-59, 62-70, 77, 85, 88, 91-92, 95, 98-105, 124-133, 141-149, 158-167,                                           170-171, 174, 177-189, 192-197, 204, 207-208, 211-212, 215-222, 228-236, 245
pyguppyclient/decode.py                                  107     85    21%   25-                                          28, 44-51, 83-101, 107-109, 112-120, 127-216, 226-227
pyguppyclient/guppy_ipc/AlignmentIndex.py                 29     14    52%   14-                                          17, 21, 25, 29-32, 36-39
pyguppyclient/guppy_ipc/AlignmentResults.py              125     78    38%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-88, 92-95                                          , 99-102, 106-109, 113-116, 120-123, 127-130, 134-137, 141-144, 148-151
pyguppyclient/guppy_ipc/BarcodeArrangementResults.py     123     82    33%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-85, 89-96, 100-1                                          07, 111-118, 122-125, 129-132, 136-139, 143-146
pyguppyclient/guppy_ipc/BarcodeKitDefinition.py           71     42    41%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-88
pyguppyclient/guppy_ipc/BarcodeMidDetectResults.py        35     18    49%   14-                                          17, 21, 25, 29-32, 36-39, 43-46
pyguppyclient/guppy_ipc/BarcodeResults.py                 47     26    45%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60
pyguppyclient/guppy_ipc/BaseModData.py                    50     29    42%   14-                                          17, 21, 25, 29-32, 36-39, 43-47, 51-54, 58-61, 65-66
pyguppyclient/guppy_ipc/CalledBlockData.py               206    140    32%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-88, 92-95                                          , 99-102, 106-109, 113-116, 120-123, 127-130, 134-137, 141-144, 148-155, 159-162                                          , 166-172, 176-183, 187-191, 195-198, 202-205, 209-210, 214-221, 225-234, 238-24                                          1, 245-246
pyguppyclient/guppy_ipc/ClientStats.py                    29     14    52%   14-                                          17, 21, 25, 29-32, 36-39
pyguppyclient/guppy_ipc/ConfigData.py                     96     65    32%   14-                                          17, 21, 25, 29-38, 42-45, 49-50, 54-63, 67-70, 74-75, 79-83, 87-90, 94-95, 99-10                                          8, 112-115, 119-120
pyguppyclient/guppy_ipc/Configuration.py                  65     38    42%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81
pyguppyclient/guppy_ipc/Content.py                         7      0   100%
pyguppyclient/guppy_ipc/FlipflopTraceData.py              59     36    39%   14-                                          17, 21, 25, 29-33, 37-40, 44-47, 51-52, 56-60, 64-67, 71-74, 78-79
pyguppyclient/guppy_ipc/MessageData.py                    48     29    40%   14-                                          17, 21, 25, 29-36, 40-43, 47-50, 54-60
pyguppyclient/guppy_ipc/ProtocolVersion.py                16      6    62%   14,                                           24-28
pyguppyclient/guppy_ipc/ReadBlockData.py                 106     69    35%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-89, 93-96                                          , 100-103, 107-108, 112-119, 123-130
pyguppyclient/guppy_ipc/ReadBlockType.py                   5      0   100%
pyguppyclient/guppy_ipc/RunlengthTraceData.py            149    100    33%   14-                                          17, 21, 25, 29-32, 36-40, 44-47, 51-54, 58-59, 63-67, 71-74, 78-81, 85-86, 90-94                                          , 98-101, 105-108, 112-113, 117-121, 125-128, 132-135, 139-140, 144-148, 152-155                                          , 159-162, 166-167, 171-175, 179-182, 186-189, 193-194
pyguppyclient/guppy_ipc/ScalingData.py                    53     30    43%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67
pyguppyclient/guppy_ipc/ScalingOverrideData.py            29     14    52%   14-                                          17, 21, 25, 29-32, 36-39
pyguppyclient/guppy_ipc/ServerStats.py                    62     38    39%   14-                                          17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-66, 70-73, 77-78
pyguppyclient/guppy_ipc/SimpleReplyData.py                35     18    49%   14-                                          17, 21, 25, 29-32, 36-39, 43-46
pyguppyclient/guppy_ipc/SimpleReplyType.py                17      0   100%
pyguppyclient/guppy_ipc/SimpleRequestData.py              35     18    49%   14-                                          17, 21, 25, 29-32, 36-39, 43-46
pyguppyclient/guppy_ipc/SimpleRequestType.py              14      0   100%
pyguppyclient/guppy_ipc/TraceData.py                       4      0   100%
pyguppyclient/guppy_ipc/__init__.py                        0      0   100%
pyguppyclient/io.py                                       24     14    42%   17-                                          23, 32, 39-40, 47-50
pyguppyclient/ipc.py                                      69     50    28%   31-                                          86, 90-143
pyguppyclient/utils.py                                    24      0   100%
--------------------------------------------------------------------------------                                          ----
TOTAL                                                   1940   1153    41%
----------------------------------------------------------------------
Ran 10 tests in 0.530s

FAILED (errors=6)
make: *** [Makefile:21: test] Error 1
```

any advice to solve the problem?
Thanks

**Comment by iiSeymour** [comment]
Hey @WaxRain 

The current version is compatible with Guppy 4.0.X - I'm just working on an update to move to 4.4.X.

**Comment by WaxRain** [comment]
**_Exception: Bad request_**

I tried Guppy v4.0.15 and pyguppyclient v0.0.7a1, then I got **_Bad request_** exception.

```
(venv3)[software/pyguppyclient$  make test
nosetests -v --with-doctest --with-coverage --cover-package pyguppyclient
Doctest: pyguppyclient.utils.bases_fmt ... ok
Doctest: pyguppyclient.utils.batches ... ok
Doctest: pyguppyclient.utils.distribute ... ok
Doctest: pyguppyclient.utils.parse_config ... ok
test the caller ... ok
test loaded configs ... ok
try and load in invalid config ... ok
test a read with state ... ok
test a read without state ... ok
test the client api without sending a read ... ok

Name                                                   Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------
pyguppyclient/__init__.py                                  7      0   100%
pyguppyclient/caller.py                                   47     17    64%   70-94
pyguppyclient/client.py                                  147     61    59%   43-44, 47, 53, 69, 77, 88, 124-133, 148-149, 158-167, 170-171, 174, 177-189, 192-197, 204, 207-208, 211-212, 215-222, 228-236, 245
pyguppyclient/decode.py                                  107     26    76%   107-109, 112-120, 146, 148, 161-163, 167-199
pyguppyclient/guppy_ipc/AlignmentIndex.py                 29     14    52%   14-17, 21, 25, 29-32, 36-39
pyguppyclient/guppy_ipc/AlignmentResults.py              125     78    38%   14-17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-88, 92-95, 99-102, 106-109, 113-116, 120-123, 127-130, 134-137, 141-144, 148-151
pyguppyclient/guppy_ipc/BarcodeArrangementResults.py     123     82    33%   14-17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-85, 89-96, 100-107, 111-118, 122-125, 129-132, 136-139, 143-146
pyguppyclient/guppy_ipc/BarcodeKitDefinition.py           71     42    41%   14-17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-88
pyguppyclient/guppy_ipc/BarcodeMidDetectResults.py        35     18    49%   14-17, 21, 25, 29-32, 36-39, 43-46
pyguppyclient/guppy_ipc/BarcodeResults.py                 47     26    45%   14-17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60
pyguppyclient/guppy_ipc/BaseModData.py                    50     29    42%   14-17, 21, 25, 29-32, 36-39, 43-47, 51-54, 58-61, 65-66
pyguppyclient/guppy_ipc/CalledBlockData.py               206    140    32%   14-17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-88, 92-95, 99-102, 106-109, 113-116, 120-123, 127-130, 134-137, 141-144, 148-155, 159-162, 166-172, 176-183, 187-191, 195-198, 202-205, 209-210, 214-221, 225-234, 238-241, 245-246
pyguppyclient/guppy_ipc/ClientStats.py                    29     14    52%   14-17, 21, 25, 29-32, 36-39
pyguppyclient/guppy_ipc/ConfigData.py                     96     52    46%   14-17, 21, 38, 45, 49-50, 54-63, 67-70, 74-75, 79-83, 87-90, 94-95, 99-108, 112-115, 119-120
pyguppyclient/guppy_ipc/Configuration.py                  65     25    62%   14-17, 21, 29-32, 36-39, 43-46, 50-53, 60, 67, 74, 81
pyguppyclient/guppy_ipc/Content.py                         7      0   100%
pyguppyclient/guppy_ipc/FlipflopTraceData.py              59     36    39%   14-17, 21, 25, 29-33, 37-40, 44-47, 51-52, 56-60, 64-67, 71-74, 78-79
pyguppyclient/guppy_ipc/MessageData.py                    48      8    83%   21, 36, 40-43, 50, 60
pyguppyclient/guppy_ipc/ProtocolVersion.py                16      0   100%
pyguppyclient/guppy_ipc/ReadBlockData.py                 106     69    35%   14-17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67, 71-74, 78-81, 85-89, 93-96, 100-103, 107-108, 112-119, 123-130
pyguppyclient/guppy_ipc/ReadBlockType.py                   5      0   100%
pyguppyclient/guppy_ipc/RunlengthTraceData.py            149    100    33%   14-17, 21, 25, 29-32, 36-40, 44-47, 51-54, 58-59, 63-67, 71-74, 78-81, 85-86, 90-94, 98-101, 105-108, 112-113, 117-121, 125-128, 132-135, 139-140, 144-148, 152-155, 159-162, 166-167, 171-175, 179-182, 186-189, 193-194
pyguppyclient/guppy_ipc/ScalingData.py                    53     30    43%   14-17, 21, 25, 29-32, 36-39, 43-46, 50-53, 57-60, 64-67
pyguppyclient/guppy_ipc/ScalingOverrideData.py            29     14    52%   14-17, 21, 25, 29-32, 36-39
pyguppyclient/guppy_ipc/ServerStats.py                    62     37    40%   14-17, 21, 29-32, 36-39, 43-46, 50-53, 57-66, 70-73, 77-78
pyguppyclient/guppy_ipc/SimpleReplyData.py                35     18    49%   14-17, 21, 25, 29-32, 36-39, 43-46
pyguppyclient/guppy_ipc/SimpleReplyType.py                17      0   100%
pyguppyclient/guppy_ipc/SimpleRequestData.py              35     18    49%   14-17, 21, 25, 29-32, 36-39, 43-46
pyguppyclient/guppy_ipc/SimpleRequestType.py              14      0   100%
pyguppyclient/guppy_ipc/TraceData.py                       4      0   100%
pyguppyclient/guppy_ipc/__init__.py                        0      0   100%
pyguppyclient/io.py                                       24      7    71%   32, 39-40, 47-50
pyguppyclient/ipc.py                                      69     22    68%   34, 44, 50, 93, 99-112, 115-117, 135-141
pyguppyclient/utils.py                                    24      0   100%
------------------------------------------------------------------------------------
TOTAL                                                   1940    983    49%
----------------------------------------------------------------------
Ran 10 tests in 4.824s

OK
python3 examples/pyguppyclient -t 5 dna_r9.4.1_450bps_fast tests/reads/testdata//multi > /dev/null
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/caller.py", line 74, in basecall_batch
    with GuppyBasecallerClient(config_name=self.config, host=self.host, port=self.port) as client:
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/client.py", line 39, in __enter__
    self.connect()
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/client.py", line 73, in connect
    config = self._load_config(self.config_name)
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/client.py", line 95, in _load_config
    loaded_configs = {Config(c).name: Config(c) for c in self.get_configs()}
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/client.py", line 91, in get_configs
    res = self.send(SimpleRequestType.GET_CONFIGS)
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/client.py", line 55, in send
    return simple_response(self.recv())
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/ipc.py", line 103, in simple_response
    raise Exception("Bad request")
Exception: Bad request
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/pyguppyclient", line 49, in <module>
    main(parser.parse_args())
  File "examples/pyguppyclient", line 32, in main
    samples = caller.basecall(files)
  File "/media/mdb2/disk3/haoy/software/pyguppyclient/venv3/lib/python3.7/site-packages/pyguppyclient/caller.py", line 61, in basecall
    return sum(pool.map(self.basecall_batch, work))
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
Exception: Bad request
make: *** [Makefile:22: test] Error 1
```

what caused this error?

**Comment by iiSeymour** [comment]
@WaxRain I've published v0.0.9 which supports Guppy 4.4.X and I see all tests passing - please give that a go.

**Comment by WaxRain** [comment]
Thanks for telling me that.
I've tried the v0.09, and it worked well with Guppy 4.4.1.

I encountered another problem.
I want to use Guppy with GPU mode, so I install cuda 11. When I run **_**guppy_basecall_server**_** by myself, it work well, while I run **_sudo service minknow start_**, the guppy can't be waked up.

when I use **_**ont-guppy_4.2.2_linux64_cuda11.tar.gz**_**, Guppy and Minknow worked well . But pyguppyclient raise an Error

```
Traceback (most recent call last):
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/site-packages/pyguppyclient/caller.py", line 74, in basecall_batch
    with GuppyBasecallerClient(config_name=self.config, host=self.host, port=self.port) as client:
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/site-packages/pyguppyclient/client.py", line 45, in __enter__
    self.connect()
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/site-packages/pyguppyclient/client.py", line 83, in connect
    self.config_name, self.pcl_client.get_error_message()
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./examples/pyguppyclient", line 49, in <module>
    main(parser.parse_args())
  File "./examples/pyguppyclient", line 32, in main
    samples = caller.basecall(files)
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/site-packages/pyguppyclient/caller.py", line 61, in basecall
    return sum(pool.map(self.basecall_batch, work))
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/media/mdb2/disk4/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
```

So can you give me any advice on the **_**version**_** selection of pyguppyclent, guppy, and minion?
Thank you!
